use_frameworks!

platform :ios, '15.5'

target 'LocalTranslatorKit_Example' do
  pod 'LocalTranslatorKit', :path => '../'
  #pod 'LocalTranslatorKit', :path => '../LocalTranslatorKit'
  target 'LocalTranslatorKit_Tests' do
    inherit! :search_paths

    
  end
end
