use_frameworks!

platform :ios, '10.0'

target 'LocalTranslatorKit_Example' do
  pod 'LocalTranslatorKit', :path => '../'

  target 'LocalTranslatorKit_Tests' do
    inherit! :search_paths

    
  end
end
